---
title: "Agricultural Production in New Zealand"
format: html
theme: cosmo
toc: true
toc-depth: 3
number-sections: true
number-depth: 3
embed-resources: true
dpi: 900
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(tidytuesdayR)
library(DT)
library(NatParksPalettes)

options(DT.options = list(pageLength = 10))
```

# Getting the data

```{r}
#| label: getting_data
#| warning: false

source("../get_data.R")

df <- get_data("2026-02-17", "dataset")
```

# Is sheep production unique in its decline?

## Sheep decline

```{r}
#| label: sheep_only

sheep <- df |> 
  
  filter(measure == "Total Sheep") |> 
  
  select(-c(value_unit, value_label)) |> 
  
  mutate(value = round(value / 1000000, 1))
```

```{r}
#| label: plotting_sheep_only

sheep |>
  
  ggplot(aes(x = year_ended_june, y = value)) +
  
  annotate(
    "rect",
    xmin = 1983, xmax = 2024,
    ymin = -Inf, ymax = 70.3,
    alpha = 0.2,
    fill = "red"
  ) +
  
  geom_line(colour = "royalblue4") +
  
  geom_point(size = 2,
             colour = "royalblue4") +
  
  labs(
    title = "New Zealand's Sheep Population Decline since 1983",
    x = NULL,
    y = "Total Sheep (Millions)",
    caption = "Data: StatsNZ"
  ) +
  
  theme_minimal(base_size = 13) +
  
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0),
    plot.caption = element_text(color = "grey50", size = 9, hjust = 1),
    
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 10, vjust = 0.2),
    axis.title.y = element_text(size = 10),
    
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.3),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 0.3),
    
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    panel.border = element_rect(color = "grey80", fill = NA, linewidth = 0.5)
  )
```
## Other types of meat production

```{r}
#| label: all_meat

all_meat <- df |> 
  
  filter(measure %in% c(
    "Total Beef Cattle",
    "Total Pigs",
    "Total goats",
    "Total Deer",
    "Total poultry"
  )) |> 
  
  select(-c(value_unit, value_label)) |> 
  
  mutate(value = round(value / 1000000, 1),
         measure = replace_values(
           measure,
           "Total Beef Cattle" ~ "Cattle",
           "Total Pigs"        ~ "Pigs",
           "Total goats"       ~ "Goats",
           "Total Deer"        ~ "Deer",
           "Total poultry"     ~ "Poultry"
         ))
```

```{r}
all_meat |>
  
  ggplot(aes(x = year_ended_june, y = value, color = measure)) +
  
  geom_line() +
  
  geom_point(size = 1.5,
             aes(shape = measure)) +
  
  scale_color_manual(values = natparks.pals("DeathValley", 6)) +
  
  labs(
    title = "New Zealand's Alternative Livestock Production",
    x = NULL,
    y = "Total Units (Millions)",
    caption = "Data: StatsNZ",
    color = "Livestock Type:",
    shape = "Livestock Type:"
  ) +
  
  theme_minimal(base_size = 13) +
  
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0),
    plot.caption = element_text(color = "grey50", size = 9, hjust = 1),
    
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 10, vjust = 0.2),
    axis.title.y = element_text(size = 10),
    
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.3),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 0.3),
    
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    panel.border = element_rect(color = "grey80", fill = NA, linewidth = 0.5),
    
    legend.position = "top",
    legend.justification = "left"
  )
```

# Which agricultural industries have shown the most production growth?

```{r}
#| label: growth_summary
#| warning: false

growth_summary <- df |> 
  
  group_by(measure, value_label) |> 
  
  arrange(year_ended_june, .by_group = TRUE) |> 
  
  summarise(
    start_value = first(value),
    end_value   = last(value),
    n_years     = n() - 1,
    abs_growth  = end_value - start_value,
    pct_growth  = ((end_value - start_value) / start_value),
    cagr        = ((end_value / start_value) ^ (1 / n_years) - 1)
  ) |> 
  
  ungroup()
```
## Absolute Growth

```{r}
#| label: top_10_abs_growth

growth_summary |> 
  
  select(
    measure,
    value_label,
    n_years,
    start_value,
    end_value,
    abs_growth
  ) |> 
  
  slice_max(abs_growth, n = 10) |> 
  
  mutate(
    start_value = round(start_value / 1000000, 2),
    end_value   = round(end_value / 1000000, 2),
    abs_growth  = round(abs_growth / 1000000, 2)
  ) |> 
  
  rename(
    "Measure"             = "measure",
    "Unit"                = "value_label",
    "Initial Value (m)"   = "start_value",
    "Current Value (m)"   = "end_value",
    "Years Measured"      = "n_years",
    "Absolute Growth (m)" = "abs_growth"
  ) |> 
  
  datatable(
    options = list(
      autowidth = TRUE,
      orderClasses = TRUE
    )
  )
```

## Relative Growth

```{r}
#| label: top_10_pct_growth

growth_summary |> 
  
  select(
    measure,
    value_label,
    n_years,
    start_value,
    end_value,
    pct_growth
  ) |> 
  
  slice_max(pct_growth, n = 10) |> 
  
  rename(
    "Measure"         = "measure",
    "Unit"            = "value_label",
    "Initial Value"   = "start_value",
    "Current Value"   = "end_value",
    "Years Measured"  = "n_years",
    "Relative Growth" = "pct_growth"
  ) |> 
  
  datatable(
    options = list(
      autowidth = TRUE,
      orderClasses = TRUE
    )
  ) |> 
  
  formatPercentage("Relative Growth", digits = 0)
```

## CAGR

```{r}
#| label: top_10_cagr

growth_summary |> 
  
  select(
    measure,
    value_label,
    n_years,
    start_value,
    end_value,
    cagr
  ) |> 
  
  slice_max(cagr, n = 10) |> 
  
  rename(
    "Measure"         = "measure",
    "Unit"            = "value_label",
    "Initial Value"   = "start_value",
    "Current Value"   = "end_value",
    "Years Measured"  = "n_years",
    "CAGR"            = "cagr"
  ) |> 
  
  datatable(
    options = list(
      autowidth = TRUE,
      orderClasses = TRUE
    )
  ) |> 
  
  formatPercentage("CAGR", digits = 0)
```

