---
title: "Science Foundation Ireland Grants Commitments"
format: html
theme: cosmo
toc: true
toc-depth: 3
number-sections: true
number-depth: 3
embed-resources: true
dpi: 900
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(DT)
library(ggridges)
library(scales)
library(lubridate)

options(DT.options = list(pageLength = 10))
```

# Getting the data

```{r}
#| label: getting_data
#| warning: false

source("../get_data.R")

sfi_grants <- get_data("2026-02-24", "sfi_grants")

```

# Which Higher Education Institute received the most grant funding?

```{r}
#| label: most_funding

hei_funding <- sfi_grants |> 
  
  group_by(research_body) |> 
  
  summarise(
    proposals    = n_distinct(proposal_id),
    total_commit = sum(current_total_commitment),
    mean_commit  = mean(current_total_commitment),
    med_commit   = median(current_total_commitment)
  )

hei_funding |> 
  
  slice_max(order_by = total_commit, n = 10) |> 
  
  rename(
    "Research Body"          = "research_body",
    "Proposals"              = "proposals",
    "Total Committed"        = "total_commit",
    "Mean Committed"         = "mean_commit",
    "Median Committed"       = "med_commit" 
  ) |> 
  
  datatable(
    options = list(
      autowidth    = TRUE,
      orderClasses = TRUE
    )
  ) |> 
  
  formatCurrency(c("Total Committed",
                   "Mean Committed",
                   "Median Committed"),
                 currency = "€",
                 digits   = 2
                 )
```


```{r}
#| label: top_10_funding
#| warning: false
#| fig-width: 8
#| fig-height: 6

top_10 <- hei_funding |> 
  
  slice_max(order_by = total_commit, n = 10) |> 
  
  pull(research_body)

sfi_grants |> 
  
  filter(research_body %in% top_10) |> 
  
  ggplot(
    aes(x = current_total_commitment, 
        y = research_body)
  ) +
  
  geom_density_ridges(
    alpha = 0.7, 
    scale = 0.9
  ) +
  
  geom_segment(
    data = hei_funding |> filter(research_body %in% top_10),
    aes(x    = mean_commit, 
        xend = mean_commit,
        y    = as.numeric(factor(research_body)),
        yend = as.numeric(factor(research_body)) + 0.9),
    colour    = "red", 
    linetype  = "dashed", 
    linewidth = 0.7,
    inherit.aes = FALSE
  ) +
  
  geom_segment(
    data = hei_funding |> 
      filter(research_body %in% top_10),
    aes(x    = med_commit, 
        xend = med_commit,
        y    = as.numeric(factor(research_body)),
        yend = as.numeric(factor(research_body)) + 0.9),
    colour    = "blue", 
    linetype  = "dashed", 
    linewidth = 0.7,
    inherit.aes = FALSE
  ) +
  
  scale_x_log10(labels = scales::label_currency(prefix = "€")) +
  
  scale_y_discrete(labels = label_wrap(20)) +
  
  labs(
    x        = "Total Commitment",
    y        = NULL,
    title    = "Distribution of Funding by Research Body (Top 10)",
    subtitle = "Blue dashed = median  |  Red dashed = mean",
     caption = "Source: www.data.gov.ie"
  ) +
  
  theme_minimal(base_size = 13) +
  
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0),
    plot.title.position = "plot",
    plot.caption = element_text(color = "grey50", size = 9, hjust = 1),
    
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 10, vjust = 0.2),
    axis.title.y = element_text(size = 10),
    
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.3),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 0.3),
    
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    panel.border = element_rect(color = "grey80", fill = NA, linewidth = 0.5),
    
    legend.position = "none"
  )
```

# How much did Science Foundation Ireland invest into research each year?

```{r}
#| label: funding_per_year

funding_year <- sfi_grants |> 
  
  group_by(
    year = year(start_date) 
  ) |> 
  
  summarise(investment = sum(current_total_commitment),
            .groups    = "drop"
  ) |> 
  
  arrange(year)
```

```{r}
#| label: funding_per_year_plot
#| fig-width: 8
#| fig-height: 6

set.seed(1)

funding_year |> 
  
  filter(year < 2025) |> 
  
  ggplot(
    aes(x = year,
        y = investment)
  ) +
  
  geom_line(
    linewidth = 0.8,
    color     = "royalblue4"
  ) +
  
  geom_point(
    shape = 21,
    fill  = "white",
    color = "royalblue4",
    stroke = 1.2
  ) +
  
  scale_x_continuous(
    breaks = scales::breaks_width(1),
    expand = expansion(mult = 0.05)
  ) +
   
  scale_y_continuous(labels = label_currency(
    prefix = "€",
    suffix = "M",
    scale  = 1e-6
  )) +
  
  labs(
    x     = NULL,
    y     = "Investment",
    title = "Investment per Year",
    caption = "Source: www.data.gov.ie"
  ) +
  
  theme_minimal(base_size = 13) +
  
  theme(
    plot.title = element_text(face = "bold", size = 14, hjust = 0),
    plot.title.position = "plot",
    plot.caption = element_text(color = "grey50", size = 9, hjust = 1),
    
    axis.text.y = element_text(size = 10),
    axis.text.x = element_text(size = 10, vjust = 0.2, angle = 90),
    axis.title.y = element_text(size = 10),
    
    panel.grid.minor = element_blank(),
    panel.grid.major.x = element_line(color = "grey90", linewidth = 0.3),
    panel.grid.major.y = element_line(color = "grey90", linewidth = 0.3),
    
    plot.background = element_rect(fill = "white", color = NA),
    panel.background = element_rect(fill = "white", color = NA),
    panel.border = element_rect(color = "grey80", fill = NA, linewidth = 0.5),
  )
```

