---
title: "winter_olympics"
format: html
theme: cosmo
toc: true
toc-depth: 3
number-sections: true
number-depth: 3
embed-resources: true
---

```{r}
#| label: setup
#| include: false

library(tidyverse)
library(tidytuesdayR)
library(DT)
library(lubridate)
library(janitor)
library(forcats)
```

# Getting the data
```{r}
#| label: get_data_function

get_data <- function(date, dataset_name){
  
  df <- tidytuesdayR::tt_load(date)
  
  df[[dataset_name]]

}
```

```{r}
#| label: getting_data
#| message: false

winter_olympics_26 <- get_data("2026-02-10", "schedule")
```

# Which sport disciplines have the most competitive events scheduled?

```{r}
#| label: events_scheduled

winter_olympics_26 |> 
  
  filter(is_training == "FALSE") |> 
  
  group_by(discipline_name) |> 
  
  summarise(
    events = n(),
    medal_events = sum(is_medal_event),
    medal_event_pct = round((medal_events / events) * 100, 1),
    .groups = "drop"
  ) |> 
  
  arrange(desc(events)) |> 
  
  datatable(
    
    colnames = c("Discipline Name"        = 2,
                 "Events Scheduled"       = 3,
                 "Medal Events Scheduled" = 4,
                 "Medal Events %"         = 5)
  )
```

# How are medal events distributed across the days of the Olympics?

## Medal Events

```{r}
#| label: medal_events

medal_events <- winter_olympics_26 |> 
  
  filter(is_medal_event == "TRUE") |> 
  
  select(
    date,
    discipline_code,
    discipline_name,
    event_description
  )

medal_events |> 
  
    datatable(
    
    colnames = c("Medal Event Date"  = 2,
                 "Discipline Code"   = 3,
                 "Discipline Name"   = 4,
                 "Event Description" = 5)
  )
```

## Medal Events per Day

```{r}
#| label: medal_events_per_day

medal_events_days <- medal_events |> 
  
  count(date, discipline_code, discipline_name, name = "n")


medal_events_days |> 
  
  group_by(date) |> 
  
  summarise(medal_events = sum(n)) |> 
  
  rename("Date" = date,
         "Medal Events" = medal_events)
```


```{r}
#| label: medal_events_per_day_plot
#| fig-width: 8
#| fig-height: 6

# Ordering disciplines by their earliest medal event
discipline_order <- medal_events_days |> 
  
  group_by(discipline_code) |> 
  
  summarise(earliest_date = min(date)) |> 
  
  arrange(earliest_date) |> 
  
  pull(discipline_code)

# Creating the tile plot
medal_events_days |> 
  
  mutate(discipline_code = factor(discipline_code, levels = rev(discipline_order))) |>
  
  ggplot(aes(x = date, y = discipline_code, fill = n)) +
  
  geom_tile(colour = "white",
            linewidth = 0.2) +
  
  geom_text(aes(label = n),
            color = "white") +
  
  scale_fill_viridis_c(name = "Medal Events") +
  
  scale_x_date(
        breaks = seq(min(medal_events_days$date),
                 max(medal_events_days$date),
                 by = "1 day"),
        
        date_labels = "%d %b") +
  
  labs(
    title = "Distribution of Medal Events Across the 2026 Milano-Cortina Winter Olympics",
    x     = "Date",
    y     = "Discipline"
  ) +
  
  theme(
    axis.text.x = element_text(angle = 50, hjust = 1),
    panel.grid.major = element_blank(),
    panel.background = element_blank()
  )
```

